config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :sites, only: :index
  resources :zones, only: :index
  resources :users
  resources :surveys do
    resources :checklists
  end
  resources :trackings, only: [:index]
  post '/users', to: 'users#create'

  resources :work_orders do
    get 'assign_user', on: :member
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    if user.it_admin?
      can :manage, :all
    elsif user.power_user?
      can :manage, :all
    elsif user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachmentable, :polymorphic => true,optional: true
  mount_uploader :attachment, AttachmentUploader
end

app/models/checklist.rb
class Checklist < ApplicationRecord
  TYPES = ['Info', 'Multiple Choice', 'Check', 'Select']
  belongs_to :survey
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :zone
  has_many :work_orders
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :checklists
  has_many :work_orders
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ROLES = ['It Admin', 'Power User', 'Admin', 'Technician']
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  belongs_to :department
  belongs_to :site
  belongs_to :zone
  has_many :assigned_work_orders, class_name: 'WorkOrder', foreign_key: 'technician_id'
  has_many :created_work_orders, class_name: 'WorkOrder', foreign_key: 'creator'
  has_many :surveys

  def it_admin
    role.name.downcase == 'it admin'
  end

  def power_user
    role.name.downcase == 'power user'
  end

  def admin
    role.name.downcase == 'admin'
  end
end

app/models/work_order.rb
class WorkOrder < ApplicationRecord
  has_many :attachments, :as => :attachmentable, :dependent => :destroy
  belongs_to :site
  belongs_to :technician, class_name: 'User', foreign_key: 'technician_id'
  belongs_to :creator, class_name: 'User', foreign_key: 'creator'
  belongs_to :survey
end

app/models/zone.rb
class Zone < ApplicationRecord
  has_many :sites
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  def index
     @sites = Site.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all #- [current_user]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :edit
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user.update_attributes(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy

  end

  private

  def user_params
    params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def generate_checklist_field(checklist)
    if checklist.item_type.downcase == 'info'
      text_field_tag 'info[]', '', placeholder: checklist.options, class: 'form-control'
    elsif checklist.item_type.downcase == 'select'
      select_tag 'choice[]', options_for_select(checklist.options.split(',')), {class: 'form-control'}
    elsif checklist.item_type.downcase == 'check'
      html = "<div class='options-multiple-choice'>"
      checklist.options.split(',').each do |op|
        html += radio_button_tag 'check[]', op, id: "check_#{op.split.join}"
        html += "<label for='check_#{op.split.join}'>#{op}</label>"
      end
      raw(html + "</div>")
    elsif checklist.item_type.downcase == 'multiple choice'
      html = "<div class='options-multiple-choice'>"
      checklist.options.split(',').each do |op|
        html += check_box_tag 'check[]', op, false, id: "check_#{op.split.join}"
        html += "<label for='check_#{op.split.join}'>#{op}</label>"
      end
      raw(html + "</div>")
    else
      checklist.options
    end
  end

  def active_menu(ct_name)
    controller_name == ct_name ? 'active' : ''
  end

  def get_technician
    role = Role.where(name: 'Technician').first
    role.users
  end
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/trackings_helper.rb
module TrackingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/sites/index.html.erb
<h2 class="public-header">Sites List </h2>

<div class="row">
  <div class="col-xs-12">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Title</th>
          <th>Zone</th>
          <th>Address</th>
          <th>Latitude</th>
          <th>Longitude</th>
        </tr>
        </thead>
        <tbody>
        <% @sites.each do |site| %>
            <tr>
              <td><%= site.title %></td>
              <td><%= site.zone.title if site.zone.present? %></td>
              <td><%= site.address %></td>
              <td><%= site.lat %></td>
              <td><%= site.lng %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <!--end of .table-responsive-->
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <div class="row">
      <div class="field form-group col-sm-6">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="field form-group col-sm-6">
        <%= f.label :department_id, 'Department' %>
        <%= f.select :department_id, options_for_select(Department.all.collect { |dp| [dp.name, dp.id] }), {}, {class: 'form-control'} %>
      </div>

      <div class="field form-group col-sm-6">
        <%= f.label :role_id, 'Role' %>
        <%= f.select :role_id, options_for_select(Role.all.collect { |role| [role.name, role.id] }), {}, {class: 'form-control'} %>
      </div>

      <div class="field form-group col-sm-6">
        <%= f.label :zone_id, 'Zone' %>
        <%= f.select :zone_id, options_for_select(Zone.all.collect { |zone| [zone.title, zone.id] }), {}, {class: 'form-control'} %>
      </div>

      <div class="field form-group col-sm-6">
        <%= f.label :site_id, 'Site' %>
        <%= f.select :site_id, options_for_select(Site.all.collect { |site| [site.title, site.id] }), {}, {class: 'form-control'} %>
      </div>

      <div class="field form-group col-sm-6">
        <%= f.label :email %>
        <%= f.email_field :email, autofocus: true, class: 'form-control' %>
      </div>

      <div class="field form-group col-sm-6">
        <%= f.label :username %>
        <%= f.text_field :username, class: 'form-control' %>
      </div>

      <div class="field form-group col-sm-6">
        <%= f.label :password %>
        <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
      </div>
    </div>


    <div class="actions clearfix text-right">
      <%= f.submit @user.new_record? ? "Create User" : 'Update User', class: 'btn btn-default' %>
    </div>
<% end %>

app/views/users/edit.html.erb
<div class="panel panel-default" style="margin-top: 10px">
  <div class="panel-headingx">
    <h4 class="public-header" style="margin: 0;">Edit User</h4>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<div style="margin-top: 10px;" class="clearfix public-header">
  <h4 class="pull-left"> All User List Including IT Admin, Power User, Admin, Technician </h4>
  <%= link_to 'Create New User', new_user_path, class: 'btn btn-primary pull-right' %>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>username</th>
    <th>Department</th>
    <th>Role/Type</th>
    <th>Site</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= user.department.name if user.department.present? %></td>
        <td><%= user.role.name if user.role.present? %></td>
        <td><%= user.site.title if user.site.present? %></td>
        <td>
          <%= link_to edit_user_path(user), class: 'btn btn-warning btn-sm', title: 'Edit' do %>
              <i class="fa fa-pencil"></i>
          <% end %>
          <%= link_to user_path(user), method: :delete, class: 'btn btn-danger btn-sm', title: 'Delete' do %>
              <i class="fa fa-trash"></i>
          <% end %>
          <%= link_to trackings_path(user_id: user), class: 'btn btn-primary btn-sm', title: 'User Tracking Details', target: '_blank' do %>
              <i class="fa fa-map-marker"></i>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="panel panel-default" style="margin-top: 10px">
  <div class="panel-headingx">
    <h4 class="public-header" style="margin: 0;">Create New User</h4>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>