config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :sites, only: :index
  resources :zones, only: :index
  resources :users
  resources :surveys do
    resources :checklists
  end
  resources :trackings, only: [:index]
  post '/users', to: 'users#create'

  resources :work_orders do
    get 'assign_user', on: :member
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    if user.it_admin?
      can :manage, :all
    elsif user.power_user?
      can :manage, :all
    elsif user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachmentable, :polymorphic => true,optional: true
  mount_uploader :attachment, AttachmentUploader
end

app/models/checklist.rb
class Checklist < ApplicationRecord
  TYPES = ['Info', 'Multiple Choice', 'Check', 'Select']
  belongs_to :survey
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :zone
  has_many :work_orders
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :checklists
  has_many :work_orders
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ROLES = ['It Admin', 'Power User', 'Admin', 'Technician']
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  belongs_to :department
  belongs_to :site
  belongs_to :zone
  has_many :assigned_work_orders, class_name: 'WorkOrder', foreign_key: 'technician_id'
  has_many :created_work_orders, class_name: 'WorkOrder', foreign_key: 'creator'
  has_many :surveys

  def it_admin
    role.name.downcase == 'it admin'
  end

  def power_user
    role.name.downcase == 'power user'
  end

  def admin
    role.name.downcase == 'admin'
  end
end

app/models/work_order.rb
class WorkOrder < ApplicationRecord
  has_many :attachments, :as => :attachmentable, :dependent => :destroy
  belongs_to :site
  belongs_to :technician, class_name: 'User', foreign_key: 'technician_id'
  belongs_to :creator, class_name: 'User', foreign_key: 'creator'
  belongs_to :survey
end

app/models/zone.rb
class Zone < ApplicationRecord
  has_many :sites
end

app/helpers/application_helper.rb
module ApplicationHelper
  def generate_checklist_field(checklist)
    if checklist.item_type.downcase == 'info'
      text_field_tag 'info[]', '', placeholder: checklist.options, class: 'form-control'
    elsif checklist.item_type.downcase == 'select'
      select_tag 'choice[]', options_for_select(checklist.options.split(',')), {class: 'form-control'}
    elsif checklist.item_type.downcase == 'check'
      html = "<div class='options-multiple-choice'>"
      checklist.options.split(',').each do |op|
        html += radio_button_tag 'check[]', op, id: "check_#{op.split.join}"
        html += "<label for='check_#{op.split.join}'>#{op}</label>"
      end
      raw(html + "</div>")
    elsif checklist.item_type.downcase == 'multiple choice'
      html = "<div class='options-multiple-choice'>"
      checklist.options.split(',').each do |op|
        html += check_box_tag 'check[]', op, false, id: "check_#{op.split.join}"
        html += "<label for='check_#{op.split.join}'>#{op}</label>"
      end
      raw(html + "</div>")
    else
      checklist.options
    end
  end

  def active_menu(ct_name)
    controller_name == ct_name ? 'active' : ''
  end

  def get_technician
    role = Role.where(name: 'Technician').first
    role.users
  end
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/trackings_helper.rb
module TrackingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fsms</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
</head>

<body>
<%= render 'shared/menu' %>
<div class="container page-wrapper">

  <div class="starter-template">
    <%= yield %>
  </div>

</div>

<footer class="footer">
  <div class="container">
    <p class="text-muted">
      Copy right &copy; www.syftet.com
      <span class="pull-right">
        General site information
      </span>
    </p>
  </div>
</footer>
<!-- /.container -->
</body>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</html>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#" style="padding: 0">
        <%= image_tag('logo.png', style: 'height: 50px') %>
      </a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if current_user.present? %>
            <li class="<%= active_menu('users') %>">
              <a href="/users">Users</a>
            </li>
            <li class="<%= active_menu('zones') %>"><%= link_to('Zones', zones_path) %></li>
            <li class="<%= active_menu('sites') %>"><%= link_to('Sites', sites_path) %></li>
            <li class="<%= active_menu('surveys') %>">
              <%= link_to 'Survey List', surveys_path %>
            </li>

            <li class="<%= active_menu('trackings') %>">
              <%= link_to 'Tracking', trackings_path %>
            </li>

            <li class="dropdown <%= active_menu('work_orders') %>" style="cursor: pointer">
              <a class="dropdown-toggle" data-toggle="dropdown">Work Order
                <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to('Work Order List', work_orders_path) %>
                </li>
                <li>
                  <a href="#">Submitted Work Order</a>
                </li>
              </ul>
            </li>
            <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %>  </li>
        <% else %>
            <li class="active"><a href="#">Home</a></li>
        <% end %>
      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
</nav>