config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :sites, only: :index
  resources :zones, only: :index
  resources :users
  resources :surveys do
    resources :checklists
  end
  resources :trackings, only: [:index]
  post '/users', to: 'users#create'

  resources :work_orders do
    get 'assign_user', on: :member
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    if user.it_admin?
      can :manage, :all
    elsif user.power_user?
      can :manage, :all
    elsif user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachmentable, :polymorphic => true,optional: true
  mount_uploader :attachment, AttachmentUploader
end

app/models/checklist.rb
class Checklist < ApplicationRecord
  TYPES = ['Info', 'Multiple Choice', 'Check', 'Select']
  belongs_to :survey
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :zone
  has_many :work_orders
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :checklists
  has_many :work_orders
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ROLES = ['It Admin', 'Power User', 'Admin', 'Technician']
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  belongs_to :department
  belongs_to :site
  belongs_to :zone
  has_many :assigned_work_orders, class_name: 'WorkOrder', foreign_key: 'technician_id'
  has_many :created_work_orders, class_name: 'WorkOrder', foreign_key: 'creator'
  has_many :surveys

  def it_admin
    role.name.downcase == 'it admin'
  end

  def power_user
    role.name.downcase == 'power user'
  end

  def admin
    role.name.downcase == 'admin'
  end
end

app/models/work_order.rb
class WorkOrder < ApplicationRecord
  has_many :attachments, :as => :attachmentable, :dependent => :destroy
  belongs_to :site
  belongs_to :technician, class_name: 'User', foreign_key: 'technician_id'
  belongs_to :creator, class_name: 'User', foreign_key: 'creator'
  belongs_to :survey
end

app/models/zone.rb
class Zone < ApplicationRecord
  has_many :sites
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  def index
     @sites = Site.all
  end
end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController

  def index
    @work_orders = WorkOrder.all
  end

  def new
    @work_order = WorkOrder.new
  end

  def create
    @work_order = WorkOrder.new(work_order_params)
    @work_order.status = 'Created'
    @work_order.creator = current_user
    respond_to do |format|
       if @work_order.save
         if params['image'].present?
           params['image'].each do |a|
             Attachment.create(attachmentable_id: @work_order.id, attachmentable_type: @work_order.class, attachment: a)
           end
         end
        format.html { redirect_to work_orders_path, notice: 'Work Order was successfully created.' }
      else
        format.html { render action: 'new' }
       end
    end
  end

  def edit
    @work_order = WorkOrder.find_by_id(params[:id])
  end

  def update
    @work_order = WorkOrder.find_by_id(params[:id])
    respond_to do |format|
      if @work_order.update_attributes(work_order_params)
        if params[:work_order][:technician_id].present?
          if @work_order.status == 'Created'
            @work_order.status = 'Assigned'
            @work_order.save
          end
        end
        if params['image'].present?
          params['image'].each do |a|
            Attachment.create(attachmentable_id: @work_order.id, attachmentable_type: @work_order.class, attachment: a)
          end
        end
        format.html { redirect_to work_orders_path, notice: 'Work Order was successfully Updated.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def destroy
    @work_order = WorkOrder.find_by_id(params[:id])
    respond_to do |format|
      if @work_order.destroy
        format.html { redirect_to work_orders_path, notice: 'Work Order was successfully deleted.' }
      else
        format.html { redirect_to work_orders_path, notice: 'Somethng Worng Try Again' }
      end
    end
  end

  def show
    @work_order = WorkOrder.find_by_id(params[:id])
  end

  def assign_user
    @work_order = WorkOrder.find_by_id(params[:id])
  end


  private

  def work_order_params
    params.require(:work_order).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def generate_checklist_field(checklist)
    if checklist.item_type.downcase == 'info'
      text_field_tag 'info[]', '', placeholder: checklist.options, class: 'form-control'
    elsif checklist.item_type.downcase == 'select'
      select_tag 'choice[]', options_for_select(checklist.options.split(',')), {class: 'form-control'}
    elsif checklist.item_type.downcase == 'check'
      html = "<div class='options-multiple-choice'>"
      checklist.options.split(',').each do |op|
        html += radio_button_tag 'check[]', op, id: "check_#{op.split.join}"
        html += "<label for='check_#{op.split.join}'>#{op}</label>"
      end
      raw(html + "</div>")
    elsif checklist.item_type.downcase == 'multiple choice'
      html = "<div class='options-multiple-choice'>"
      checklist.options.split(',').each do |op|
        html += check_box_tag 'check[]', op, false, id: "check_#{op.split.join}"
        html += "<label for='check_#{op.split.join}'>#{op}</label>"
      end
      raw(html + "</div>")
    else
      checklist.options
    end
  end

  def active_menu(ct_name)
    controller_name == ct_name ? 'active' : ''
  end

  def get_technician
    role = Role.where(name: 'Technician').first
    role.users
  end
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/trackings_helper.rb
module TrackingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/work_orders/_assign_form.html.erb
<%= form_for(@work_order) do |f| %>
    <% get_technician.each do |user| %>
        <%= f.radio_button :technician_id, user.id %> <%= user.name %><br/>
    <% end %>
    <div class="modal-footer">
     <%= f.submit %>
    </div>
<% end %>

app/views/work_orders/_assign_user.html.erb
<div class="modal fade" id="assign-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Assign User</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      </div>
    </div>
  </div>
</div>

app/views/work_orders/_form.html.erb
<%= form_for(@work_order, :html => { :multipart => true }) do |f| %>
    <div class="row">
      <div class="field form-group col-sm-6">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="field form-group col-sm-6">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>

      <div class="field form-group col-sm-6">
        <%= f.label :site_id, 'Site' %>
        <%= f.select :site_id, options_for_select(Site.all.collect { |site| [site.title, site.id] }), {}, {class: 'form-control'} %>
      </div>

      <div class="field form-group col-sm-6">
        <%= f.label :survey_id, 'Survey' %>
        <%= f.select :survey_id, options_for_select(Survey.all.collect { |survey| [survey.title, survey.id] }), {}, {class: 'form-control'} %>
      </div>

      <div class="field form-group col-sm-6">
        <%= f.label :start_date %>
        <%= f.text_field :start_date, class: 'form-control datepicker' %>
      </div>

      <div class="field form-group col-sm-6">
        <%= f.label :end_date %>
        <%= f.text_field :end_date, class: 'form-control datepicker' %>
      </div>
      <div class="col-sm-12" style="margin-bottom: 10px;">
        <% unless (@work_order.new_record?) %>
            <% if @work_order.attachments.present? %>
                <div class="listing-image-thumbnail-stripe slider-nav-thumbnails listing_attachments" id="thumbnail-stripe">
                  <% @work_order.attachments.each do |att| %>
                      <div class="col-sm-1">
                        <%= image_tag att.attachment, style: 'width: 60px' %>
                      </div>
                  <% end %>
                </div>
            <% end %>
        <% end %>
      </div>

      <div class="field form-group col-sm-6">
        <label class="btn btn-primary" for="my-file-selector">
          <input id="my-file-selector" type="file" multiple="multiple"name="[image][]" style="display:none;">
          Upload attachment
        </label>
      </div>
    </div>



    <div class="actions clearfix text-right">
      <%= f.submit @work_order.new_record? ? "Create Work Worder" : 'Update Work Worder', class: 'btn btn-default' %>
    </div>
<% end %>

<script type="text/javascript">
    $(document).ready(function(){
        $('.datepicker').datepicker();
    });
</script>

app/views/work_orders/assign_user.js.erb
$('#assign-modal').modal().find('.modal-body').html("<%= escape_javascript(render 'assign_form').html_safe %>");

app/views/work_orders/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 style>Edit Work Order</h4>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/work_orders/index.html.erb
<div style="margin-top: 10px;" class="clearfix public-header">
  <h4 class="pull-left"> Work Order List </h4>
  <%= link_to 'Create Work Order', new_work_order_path, class: 'btn btn-primary pull-right' %>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Site</th>
    <th>Survey</th>
    <th>Assign to</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Creator</th>
    <th>Status</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <% @work_orders.each do |work_order| %>
      <tr>
        <td><%= work_order.title %></td>
        <td><%= work_order.description %></td>
        <td><%= work_order.site.title if work_order.site.present? %></td>
        <td><%= work_order.survey_id  %></td>
        <td><%= work_order.technician.name if work_order.technician.present? %></td>
        <td><%= work_order.start_date %></td>
        <td><%= work_order.end_date %></td>
        <td><%= work_order.creator.name %></td>
        <td><%= work_order.status %></td>
        <td>

          <%= link_to assign_user_work_order_path(work_order), remote: true, class: 'btn btn-primary', title: "#{work_order.technician.present? ? 'Reassign' : 'Assign'}" do %>
              <i class="fa fa-user-plus"></i>
          <% end %>

          <%= link_to work_order_path(work_order), class: 'btn btn-warning', title: 'Show' do %>
              <i class="fa fa-eye"></i>
          <% end %>

          <%= link_to edit_work_order_path(work_order), class: 'btn btn-warning', title: 'Edit' do %>
              <i class="fa fa-pencil"></i>
          <% end %>
          <%= link_to work_order_path(work_order), method: :delete, class: 'btn btn-danger', title: 'Delete' do %>
              <i class="fa fa-trash"></i>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>


<!-- Modal -->
<%= render 'assign_user' %>

app/views/work_orders/new.html.erb
<div class="panel panel-default" style="margin-top: 10px;">
  <div class="panel-headingx">
    <h4  class="public-header" style="margin: 0;">Create New Work Order</h4>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/work_orders/show.html.erb
<h4 class="public-header">Work Order Details</h4>
<div class="panel panel-default">
  <div class="panel-body">
    <div class="col-sm-4">
      <div class="panel panel-default">
        <div class="panel-headingx">
          <h4 class="public-header" style="margin: 0">Zone Information</h4>
        </div>
        <div class="panel-body">
          <table class="table table-striped">
            <tbody>
            <tr>
              <th>Title</th>
              <th><%= @work_order.site.zone.title %></th>
            </tr>

            <tr>
              <th>Address</th>
              <th><%= @work_order.site.zone.address %></th>
            </tr>

            <tr>
              <th>ID</th>
              <th><%= @work_order.site.zone.id %></th>
            </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-headingx">
          <h4 class="public-header" style="margin: 0">Site Information</h4>
        </div>
        <div class="panel-body">
          <table class="table table-striped">
            <tbody>
            <tr>
              <th>Title</th>
              <th><%= @work_order.site.title %></th>
            </tr>

            <tr>
              <th>Address</th>
              <th><%= @work_order.site.address %></th>
            </tr>

            <tr>
              <th>Latitude</th>
              <th><%= @work_order.site.lat %></th>
            </tr>
            <tr>
              <th>Longitude</th>
              <th><%= @work_order.site.lng %></th>
            </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="col-sm-8">
      <div class="panel panel-default">
        <div class="panel-headingx">
          <h4 class="public-header" style="margin: 0">Survey Details</h4>
        </div>
        <div class="panel-body">
          <div class="panel-body">
            <h4> <%= @work_order.survey.title %> </h4>
            <h3>
              Checklist Items
            </h3>
            <table class="table survey-checklist">
              <thead>
              <tr>
                <th>Title</th>
                <th>Outcome Options</th>
                <th></th>
              </tr>
              </thead>
              <tbody>
              <% @work_order.survey.checklists.each do |checklist| %>
                  <tr class="checklist-item-<%= checklist.id %>">
                    <td> <%= checklist.title %> </td>
                    <td> <%= generate_checklist_field(checklist) %> </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>